kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30081
        hostPort: 8081
        protocol: TCP
    extraMounts:
      - hostPath: ../data/mariadb   # Carpeta en tu máquina host
        containerPath: /data/mariadb
      - hostPath: ../data/matomo    # Carpeta en tu máquina host
        containerPath: /data/matomo
