apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
  template:
    metadata:
      labels:
        app: matomo
    spec:
      containers:
      - name: matomo
        image: juanedriss/matomo-custom:latest
        env:
          - name: MATOMO_DATABASE_HOST
            value: "mariadb"
          - name: MATOMO_DATABASE_ADAPTER
            value: "pdo_mysql"
          - name: MATOMO_DATABASE_TABLES_PREFIX
            value: "matomo_"
          - name: MATOMO_DATABASE_USERNAME
            value: "matomo"
          - name: MATOMO_DATABASE_PASSWORD
            value: "matomo_pass"
          - name: MATOMO_DATABASE_DBNAME
            value: "matomo"
        ports:
          - containerPort: 80
        volumeMounts:
          - name: matomo-storage
            mountPath: /var/www/html
      volumes:
        - name: matomo-storage
          persistentVolumeClaim:
            claimName: pvc-matomo
