apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-matomo
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/matomo
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
